name = "Calmato"
uuid = "b7e6607a-8820-4d8f-a72b-781907f693e6"
authors = ["Shun Ueda"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
